#!/usr/bin/env python3
"""Decode HeartCodec frames JSON using the Python reference model flow."""

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path.home() / "repos" / "heartlib" / "src"))

import torch
from heartlib.heartcodec.modeling_heartcodec import HeartCodec


def write_wav(path: Path, audio: torch.Tensor, sample_rate: int) -> None:
    import scipy.io.wavfile as wavfile

    audio_np = audio.detach().cpu().numpy()
    if audio_np.ndim == 3 and audio_np.shape[1] == 1:
        audio_np = audio_np[:, 0, :]
    elif audio_np.ndim == 1:
        audio_np = audio_np[None, :]
    if audio_np.ndim != 2:
        raise ValueError(f"expected [channels, frames] audio, got {audio_np.shape}")
    audio_np = (audio_np * 32767).clip(-32768, 32767).astype("int16")
    wavfile.write(path, sample_rate, audio_np.T)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--model-dir", required=True, help="Path to HeartCodec model directory")
    parser.add_argument("--frames-json", required=True, help="Path to frames JSON file")
    parser.add_argument("--output", required=True, help="Output WAV file path")
    parser.add_argument("--duration", type=float, default=10.0, help="Audio duration in seconds")
    parser.add_argument("--num-steps", type=int, default=10, help="ODE steps")
    parser.add_argument("--guidance-scale", type=float, default=1.25, help="CFG scale")
    parser.add_argument("--seed", type=int, default=0, help="Torch RNG seed")
    parser.add_argument(
        "--initial-latent-json",
        help="Path to shared initial latent JSON generated by maolan-generate",
    )
    args = parser.parse_args()

    torch.manual_seed(args.seed)

    print(f"Loading HeartCodec from {args.model_dir}")
    model = HeartCodec.from_pretrained(
        args.model_dir,
        device_map="cpu",
        dtype=torch.float32,
        ignore_mismatched_sizes=True,
    )
    model.eval()

    with open(args.frames_json) as f:
        data = json.load(f)
    frames = data["frames"]
    codes = torch.tensor(frames, dtype=torch.long).transpose(0, 1)
    print(f"Loaded frames tensor: {tuple(codes.shape)}")

    initial_latent = None
    if args.initial_latent_json:
        with open(args.initial_latent_json) as f:
            latent_payload = json.load(f)
        dims = latent_payload["dims"]
        initial_latent = torch.tensor(latent_payload["data"], dtype=torch.float32).reshape(dims)

    with torch.no_grad():
        duration = codes.shape[-1] / 12.5
        original_randn = torch.randn
        used_initial_latent = False
        matching_randn_calls = 0

        def patched_randn(*shape, **kwargs):
            nonlocal used_initial_latent, matching_randn_calls
            if initial_latent is not None and not used_initial_latent:
                requested_shape = shape
                if len(shape) == 1 and isinstance(shape[0], (tuple, list, torch.Size)):
                    requested_shape = tuple(shape[0])
                if tuple(requested_shape) == tuple(initial_latent.shape):
                    matching_randn_calls += 1
                    if matching_randn_calls == 2:
                        used_initial_latent = True
                        tensor = initial_latent
                        device = kwargs.get("device")
                        dtype = kwargs.get("dtype")
                        if device is not None:
                            tensor = tensor.to(device=device)
                        if dtype is not None:
                            tensor = tensor.to(dtype=dtype)
                        return tensor.clone()
            return original_randn(*shape, **kwargs)

        try:
            if initial_latent is not None:
                torch.randn = patched_randn
            audio = model.detokenize(
                codes,
                duration=duration,
                num_steps=args.num_steps,
                disable_progress=True,
                guidance_scale=args.guidance_scale,
            )
        finally:
            torch.randn = original_randn
        print(f"Decoded audio tensor: {tuple(audio.shape)}")

    write_wav(Path(args.output), audio, 48_000)
    print(f"Saved audio to {args.output}")


if __name__ == "__main__":
    main()
